; DIGIT DEFS
#DEFINE DIGIT_ZERO 0xC0
#DEFINE DIGIT_ONE 0xF9
#DEFINE DIGIT_TWO 0xA4
#DEFINE DIGIT_THREE 0xB0
#DEFINE DIGIT_FOUR 0x99
#DEFINE DIGIT_FIVE 0x92
#DEFINE DIGIT_SIX 0x82
#DEFINE DIGIT_SEVEN 0xF8
#DEFINE DIGIT_EIGHT 0x80
#DEFINE DIGIT_NINE 0x98
    
#DEFINE NUM_ONE 0x3E
#DEFINE NUM_TWO 0x3D
#DEFINE NUM_THREE 0x37
#DEFINE NUM_FOUR 0x3B
#DEFINE NUM_FIVE 0x1F
#DEFINE NUM_SIX 0x2F
    
#DEFINE MEM_DIGIT_START 0x30
#DEFINE MEM_COUNTER MEM_DIGIT_START + 10
#DEFINE MEM_INNER_DELAY MEM_DIGIT_START + 11
#DEFINE VAL_INNER_DELAY 0xFF
#DEFINE MEM_OUTER_DELAY MEM_DIGIT_START + 12
#DEFINE VAL_OUTER_DELAY 0xAF
    
#INCLUDE<P16F877A.INC>
    __CONFIG _DEBUG_OFF&_CP_ALL&_WRT_HALF&_CPD_ON&_LVP_OFF&_BODEN_OFF&_PWRTE_ON&_WDT_OFF&_HS_OSC
    ORG 00H
    
    BSF STATUS, RP0 ; SELECT BANK 1
    BCF STATUS, RP1
    
    MOVLW 06H ; SET OUTS TO DIGITAL
    MOVWF ADCON1
    
    BCF STATUS, RP0 ; SELECT BANK 0
    
    MOVLW 0x09
    MOVWF MEM_COUNTER
    
    ; MOVE ALL DIGITS INTO MEMORY
    MOVLW DIGIT_ZERO
    MOVWF MEM_DIGIT_START
    
    MOVLW DIGIT_ONE
    MOVWF MEM_DIGIT_START + 1
    
    MOVLW DIGIT_TWO
    MOVWF MEM_DIGIT_START + 2
    
    MOVLW DIGIT_THREE
    MOVWF MEM_DIGIT_START + 3
    
    MOVLW DIGIT_FOUR
    MOVWF MEM_DIGIT_START + 4
    
    MOVLW DIGIT_FIVE
    MOVWF MEM_DIGIT_START + 5
    
    MOVLW DIGIT_SIX
    MOVWF MEM_DIGIT_START + 6
    
    MOVLW DIGIT_SEVEN
    MOVWF MEM_DIGIT_START + 7
    
    MOVLW DIGIT_EIGHT
    MOVWF MEM_DIGIT_START + 8
    
    MOVLW DIGIT_NINE
    MOVWF MEM_DIGIT_START + 9
    
    BSF STATUS, RP0 ; SELECT BANK 1
    BCF STATUS, RP1
        
    MOVLW B'11000000' ; SET FIRST SIX PORTS TO OUTPUT
    MOVWF TRISA 
    
    ; SEGMENTS
    MOVLW 00H ; SET ALL PINS TO OUTPUT
    MOVWF TRISD
    
    BCF STATUS, RP0 ; SELECT BANK 0
    
    MOVLW NUM_THREE ; b'11111110' ; ONLY DISPLAY ON THE FIRST DISP
    MOVWF PORTA
    
    GOTO LOOP_ZERO_TO_NINE
    
SET_DIGIT:
    MOVLW MEM_DIGIT_START
    ADDWF MEM_COUNTER, W
    MOVWF FSR
    MOVF INDF, W
    MOVWF PORTD
    RETURN

COUNT:
    DECFSZ MEM_COUNTER, 1
	RETURN
    MOVLW 0x09
    MOVWF MEM_COUNTER
    
DELAY:
    MOVLW VAL_OUTER_DELAY
    MOVWF MEM_OUTER_DELAY
    GOTO OUTER_DELAY_LOOP
    
OUTER_DELAY_LOOP:
    MOVLW VAL_INNER_DELAY
    MOVWF MEM_INNER_DELAY
    GOTO INNER_DELAY_LOOP
    
INNER_DELAY_LOOP:
    DECFSZ MEM_INNER_DELAY, F
    GOTO INNER_DELAY_LOOP
    
    DECFSZ MEM_OUTER_DELAY, F
    GOTO OUTER_DELAY_LOOP
    RETURN

LOOP_ZERO_TO_NINE:
    CALL SET_DIGIT
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL COUNT
    GOTO LOOP_ZERO_TO_NINE
    
LOOP:
    NOP
    GOTO LOOP
    END